### ISSUE TITLE
Transmutation bug

### ISSUE THREAD

**Issue by linux-kernelle** [DinnerBeef/Compressium#10]
While I do enjoy (overpowered) magic mods and transmuting materials, I would like for utility mods to be separate from magic mods. I found this bug that allows me to not only create matter out of thin air, but also transmute compressed blocks.

![Screenshot_20200826_134626](https://user-images.githubusercontent.com/69362688/91666624-fd496c00-eb06-11ea-95ba-06474f42de1d.png)

![Screenshot_20200826_134654](https://user-images.githubusercontent.com/69362688/91666636-15b98680-eb07-11ea-9ed6-3550920401fe.png)

**Comment by DinnerBeef** [comment]
What version of the mod are you on. And what level are the blocks in the crafting grid

**Comment by linux-kernelle** [comment]
The mod's version is 1.0.24 and the the blocks are Compressed Dirt (1x) and Compressed Gravel (1x).

**Comment by DinnerBeef** [comment]
just tested this and i do not get the issue are your sure you did not change something on your end?
