### ISSUE TITLE
Compressium 1.16.3

### ISSUE THREAD

**Issue by TariiPanda** [DinnerBeef/Compressium#17]
Hi, the most recent version of Compressium seems to not work on my server, and when I try to click on the mod inside my forge client it crashes and gives me the error:
"The game crashed whilst mouseclicked event handler
Error: java.lang.ArrayIndexOutOfBoundsException: 0
Exit Code: -1"

**Comment by DinnerBeef** [comment]
I just tested this I have no issues. What version of the mod are you on?

**Comment by TariiPanda** [comment]
1.16.3 as the title says

**Comment by DinnerBeef** [comment]
Yea i have no idea how that happening does not appear to be me
