### ISSUE TITLE
Add blackstone to Compressium (1.16.3)

### ISSUE THREAD

**Issue by tanyan-tanyan** [DinnerBeef/Compressium#19]
Hi, I love your mod very much.
Is it possible to add blackstone to this mod? https://i.imgur.com/P7xR5R7.png

**Comment by DinnerBeef** [comment]
https://github.com/DinnerBeef/Compressium/issues/20

**Comment by LlubNek** [comment]
also soul soil, basalt and magma block (newish nether blocks in general)

**Comment by DinnerBeef** [comment]
i should get around to this

**Comment by DinnerBeef** [comment]
Plan on doing this in more of an addons mod. This is done so not to have to many blocks in one mod an let people choice what they want
