### ISSUE TITLE
[suggestion] Compressed Ice ;)

### ISSUE THREAD

**Issue by Maxwelljones** [DinnerBeef/Compressium#20]
Would be lovely to have compressed Ice as well :)
Love to make compressed ice-cream!

Thanks for such a great mod ^^

**Comment by DinnerBeef** [comment]
https://minecraft.gamepedia.com/Packed_Ice

**Comment by Maxwelljones** [comment]
Was thinking more of x9 compressed ice, but thanks anyway for your quick reply ;)
