### ISSUE TITLE
[Enhancement] [1.16.4] Tag Capabilities

### ISSUE THREAD

**Issue by TwilightPSN** [DinnerBeef/Compressium#21]
Is it possible to add the ability to make compressed blocks from anything tagged for that block. Oh the biomes youll go adds a bunch of blocks tagged as stone and cobble and would love to use them to be able to make these blocks as well.

**Comment by DinnerBeef** [comment]
just because something is tagged on cobble does not mean it should be made into a compressed block of cobblestone. Only cobblestone will be able to make it
